name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.x
      
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
        
      - name: Standardrb check
        run: bundle exec standardrb